config/routes.rb
Caltrain::Application.routes.draw do
  root :to => 'home#index'
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get '/match/:id' => "trips#matching_offers", :as => "match_trip"
  get "home" =>"home#index"
  resources :users
  resources :sessions
  resources :offers
  resources :trips
  resources :shares


end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  belongs_to :train
  has_one :share

  attr_accessible :off_station, :on_station, :train_id, :user_id, :wifi_duration, :on_station_time, :off_station_time


# the original version of this method-(self.off_station_time.split(':')[1].to_f/60) +self.off_station_time.split(':')[0].to_f
  def self.decimal_time(x)
    (x.split(':')[1].to_f/60) + (x.split(':')[0].to_f)
  end

  def duration
    self.wifi_duration.to_f/60
  end

  def on_time
    Trip.decimal_time(self.on_station_time)
  end

  def off_time
    Trip.decimal_time(self.off_station_time)
  end

  # @my_trip.new_matching_offers
  #
  # Returns an array of Offer objects.
  def matching_offers
    offers_on_train = Offer.where(:train_id => train_id)

    # I will add matching offers to this array:
    matching_offers_array = []

    offers_on_train.each do |offer|

      # Prerequisite Check:
      if offer.duration >= duration && offer.on_time < (off_time - duration)

        # If passes prereqs, then either this group must pass...
        if offer.on_time <= on_time && offer.off_time >= (on_time + duration)
          matching_offers_array << offer

        # ...or this group must pass.
        elsif offer.on_time >= on_time && offer.off_time >= (off_time - duration)
          matching_offers_array << offer
        end
      end
    end

    matching_offers_array.uniq
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  # skip_before_filter :require_login, :only => [:index]


  # GET /trips
  # GET /trips.json
  def matching_offers
    @trip = Trip.find(params[:id])
    @matching_offers = @trip.matching_offers
    @share = Share.new
  end

  def index
    @trips = Trip.where(:user_id => current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @trip = Trip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.create(params[:trip])
    @start_time=@trip.on_station_time
    @start_station=@trip.on_station
    @matching_trains=Train.where("schedule-> '#{@start_time}' = '#{@start_station}'")
    @train_id=@matching_trains.first.id
    @stop_time=@matching_trains.first.schedule.key(@trip.off_station)



    respond_to do |format|
      if @trip.update_attributes(:train_id=>@train_id, :off_station_time=>@stop_time)
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render json: @trip, status: :created, location: @trip }
      else
        format.html { render action: "new" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div id="form">

    <div class="field">
      <%= f.text_field :on_station %>
      <div class="l">Leaving from</div>

    </div>
    <div class="field">
      <%= f.text_field :on_station_time%></div>
      <div class="l">Time</div>


    <div class="field">
      <%= f.text_field :off_station %></div>
    <div class="l">Arriving at</div>

    <div class="field">
      <%= f.number_field :wifi_duration %>
    </div>
    <div class="l">Duration need</div>

    <div class="actions">
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.submit %>
    </div>
  <% end %>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<div class="description">I need wifi tomorrow!</div>

<div class="s_box">
<div class="s"><%= link_to 'New Trip', new_trip_path %></div>

<% @trips.each do |trip| %>


    <div class="s">On station:<%= trip.on_station %></div>
    <div class="s">Off station:<%= trip.off_station %></div>
    <div class="s">Wifi duration: <%= trip.wifi_duration %></div>
    <div class="s"><%= link_to 'Details', trip %></div>
    <div class="s"><%= link_to 'Edit', edit_trip_path(trip) %></div>


<% end %>
</div>
<br/>
<br/>
<br/>
<br/>

app/views/trips/matching_offers.erb
<div class="details_box">
  <h1>MATCHED!</h1>
   <h1>here is your match <%= @trip.matching_offers.first.user.email %>
   </h1>

    <div class="s"><%= link_to 'See Network Info', share_path(@trip) %></div>

  <%= form_for(@share) do |f| %>
    <% if @share.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@share.errors.count, "error") %> prohibited this share from being saved:</h2>

        <ul>
        <% @share.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.hidden_field :trip_id,:value=>@trip.id %>
    </div>
    <div class="field">
      <%= f.hidden_field :offer_id,:value=>@trip.matching_offers.first.id %>
    </div>


  <% end %>

app/views/trips/new.html.erb
<div id="tripcreate"><h1>Looking for wifi.</h1>
  <h1>Enter in your trip information</h1>
  <h1>and we will find some one who can</h1>
  <h1>provide the service.</h1>
</div>

<%= render 'form' %>

app/views/trips/show.html.erb
<div class="details_box">
<p class="details">


  <p class="details">You will be riding train #<%= @trip.train_id %> </p>
  <p class="details">departing <%= @trip.on_station %> at <%= @trip.on_station_time %> </p>
  <p class="details"> and will be arriving at <%= @trip.off_station %> at <%= @trip.off_station_time %> </p>
  <p class="details"> and you will be needing wifi for <%= @trip.wifi_duration %> minutes.</p>
</p>

<div class="details">

<%= link_to 'Match Me', match_trip_path(@trip) %>
</div>
</div>
<!-- <p>
  <b>User:</b>
  <%= @trip.user_id %>
</p>

<p>
  <b>Train:</b>
  <%= @trip.train_id %>
</p>

<p>
  <b>On station:</b>
  <%= @trip.on_station %>
</p>

<p>
  <b>On station TIME:</b>
  <%= @trip.on_station_time %>
</p>

<p>
  <b>Off station:</b>
  <%= @trip.off_station %>
</p>

<p>
  <b>Off station TIME:</b>
  <%= @trip.off_station_time %>
</p>
<p>
  <b>Wifi duration:</b>
  <%= @trip.wifi_duration %>
</p>
 -->