config/routes.rb
Caltrain::Application.routes.draw do
  root :to => 'home#index'
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get '/match/:id' => "trips#matching_offers", :as => "match_trip"
  get "home" =>"home#index"
  resources :users
  resources :sessions
  resources :offers
  resources :trips
  resources :shares


end

app/models/share.rb
class Share < ActiveRecord::Base
  belongs_to :train
  belongs_to :offer
  attr_accessible :network_name, :network_password, :offer_id, :trip_id, :user_rating, :wifi_rating
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  # GET /shares
  # GET /shares.json
  def index
    @shares = Share.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shares }
    end
  end

  # GET /shares/1
  # GET /shares/1.json
  def show
    @share = Share.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @share }
    end
  end

  # GET /shares/new
  # GET /shares/new.json
  def new
    @share = Share.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @share }
    end
  end

  # GET /shares/1/edit
  def edit
    @share = Share.find(params[:id])
  end

  # POST /shares
  # POST /shares.json
  def create
    @share = Share.new(params[:share])

    respond_to do |format|
      if @share.save
        format.html { redirect_to @share, notice: 'Share was successfully created.' }
        format.json { render json: @share, status: :created, location: @share }
      else
        format.html { render action: "new" }
        format.json { render json: @share.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shares/1
  # PUT /shares/1.json
  def update
    @share = Share.find(params[:id])

    respond_to do |format|
      if @share.update_attributes(params[:share])
        format.html { redirect_to @share, notice: 'Share was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @share.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shares/1
  # DELETE /shares/1.json
  def destroy
    @share = Share.find(params[:id])
    @share.destroy

    respond_to do |format|
      format.html { redirect_to shares_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/views/shares/_form.html.erb
<%= form_for(@share) do |f| %>
  <% if @share.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@share.errors.count, "error") %> prohibited this share from being saved:</h2>

      <ul>
      <% @share.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class id="form">
  <div class="field">
    <%= f.text_field :network_name %>
    <div class="l">Network Name</div>

  </div>
  <div class="field">
    <%= f.text_field :network_password %>
    <div class="l">Network ID</div>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/shares/edit.html.erb
<h1>Editing share</h1>

<%= render 'form' %>

<%= link_to 'Show', @share %> |
<%= link_to 'Back', shares_path %>

app/views/shares/index.html.erb
<h1>Listing shares</h1>

<table>
  <tr>
    <th>Trip</th>
    <th>Offer</th>
    <th>Wifi rating</th>
    <th>User rating</th>
    <th>Network name</th>
    <th>Network password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shares.each do |share| %>
  <tr>
    <td><%= share.trip_id %></td>
    <td><%= share.offer_id %></td>
    <td><%= share.wifi_rating %></td>
    <td><%= share.user_rating %></td>
    <td><%= share.network_name %></td>
    <td><%= share.network_password %></td>
    <td><%= link_to 'Show', share %></td>
    <td><%= link_to 'Edit', edit_share_path(share) %></td>
    <td><%= link_to 'Destroy', share, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Share', new_share_path %>

app/views/shares/new.html.erb
<h1>New share</h1>

<%= render 'form' %>

app/views/shares/show.html.erb
<div class="match_box">

  <div class="s">You have a Match. </div>

  <div class="s"> Network info</div>
  <div class="s">
    <b>Network name:</b>
   <%= @share.network_name %>
  </div>

  <div class="s">
    <b>Network password:</b>
    <%= @share.network_password %>
  </div>
  <div class="s">
    <%= link_to 'Edit', edit_share_path(@share) %>
  </div>
</div>