config/routes.rb
Caltrain::Application.routes.draw do
  root :to => 'home#index'
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get '/match/:id' => "trips#matching_offers", :as => "match_trip"
  get "home" =>"home#index"
  resources :users
  resources :sessions
  resources :offers
  resources :trips
  resources :shares


end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :user
  belongs_to :train
  has_one :share

  attr_accessible :off_station, :on_station, :train_id, :user_id, :on_station_time, :off_station_time

  def self.decimal_time(x)
    (x.split(':')[1].to_f/60) + (x.split(':')[0].to_f)
  end

  def on_time
    Offer.decimal_time(self.on_station_time)
  end

  def off_time
    Offer.decimal_time(self.off_station_time)
  end

  def duration
    off_time - on_time
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.where(:user_id => current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offers }
    end
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
    @offer = Offer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @offer }
    end
  end

  # GET /offers/new
  # GET /offers/new.json
  def new
    @offer = Offer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @offer }
    end
  end

  # GET /offers/1/edit
  def edit
    @offer = Offer.find(params[:id])
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.create(params[:offer])
    @start_time=@offer.on_station_time
    @start_station=@offer.on_station
    @matching_trains=Train.where("schedule-> '#{@start_time}' = '#{@start_station}'")
    @train_id=@matching_trains.first.id
    @stop_time=@matching_trains.first.schedule.key(@offer.off_station)



    respond_to do |format|
      if @offer.update_attributes(:train_id=>@train_id, :off_station_time=>@stop_time)
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render json: @offer, status: :created, location: @offer }
      else
        format.html { render action: "new" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /offers/1
  # PUT /offers/1.json
  def update
    @offer = Offer.find(params[:id])

    respond_to do |format|
      if @offer.update_attributes(params[:offer])
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to offers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="form">
  <div class="field">
    <%= f.text_field :on_station %>
    <div class="l">Leaving from</div>

  </div>
  <div class="field">
    <%= f.text_field :on_station_time%>
    <div class="l">Time</div>

  </div>
  <div class="field">
    <%= f.text_field :off_station %>
    <div class="l">Arriving at</div>

  </div>
  <div class="actions">
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<div class="description">I have wifi that I don't use!</div>
<div class="o_box">

    <div class="s"><%= link_to 'New Offer', new_offer_path %></div>


<% @offers.each do |offer| %>

    <div><%= offer.user_id %></div>

    <div class="s"> Leaving from <%= offer.on_station %></div>
    <div class="s">Arriving at <%= offer.off_station %></div>
    <div class="s"><%= link_to 'Details', offer %></div>
    <div class="s"><%= link_to 'Edit', edit_offer_path(offer) %></div>

<% end %>
</div>
<br />

app/views/offers/new.html.erb
<div id="tripcreate"><h1>Give me some money!</h1>
  <h1>Enter in your trip information</h1>
  <h1>and we'll find some one who will</h1>
  <h1>pay to use your mobile hotspot!</h1>
</div>
<%= render 'form' %>

app/views/offers/show.html.erb
<div class="details_box">

  <div class="details">
  This is when you can offer your wifi:

  <div class="details">

<p class="details">


  You ride the #<%= @offer.train_id %> that departs <%= @offer.on_station %> at <%= @offer.on_station_time %> and arrives <%= @offer.off_station %> at <%= @offer.off_station_time %>.
</p>

<%= link_to 'Do I have a match? ', share_path(@offer) %> |
<%= link_to 'Edit', edit_offer_path(@offer) %>

</div>
</div>



<!-- <p id="notice"><%= notice %></p>

<p>
  <b>Offer.id:</b>
  <%= @offer.id %>
</p>

<p>
  <b>User:</b>
  <%= @offer.user_id %>
</p>

<p>
  <b>Train:</b>
  <%= @offer.train_id %>
</p>

<p>
  <b>On station:</b>
  <%= @offer.on_station %>
</p>

<p>
  <b>On station TIME:</b>
  <%= @offer.on_station_time %>
</p>

<p>
  <b>Off station:</b>
  <%= @offer.off_station %>
</p>

  <b>Off station TIME:</b>
  <%= @offer.off_station_time %>
</p>


 -->